### ISSUE TITLE
Cannot be displayed on right side of large screens?

### ISSUE THREAD

**Issue by sdondley** [keycastr/keycastr#173]
I have an iMac5K which has a screen resolution of 5120 x 2880.

When I move the keycastr display to about 2/3rds of the way on the right hand of the screen, it disappears permanently. I have to restart the app to get it back. Please advise.

**Comment by rtgoodwin** [comment]
I believe this is this: https://github.com/keycastr/keycastr/issues/175

**Comment by akitchen** [comment]
Apologies for missing this issue before! Yes, there is a related issue in #175 but I'm surprised to see this happen on a single (albeit large) screen. The fix for #175 should also address this -- the backing frame for the visualizer is unreasonably large and things don't go well when it's mostly offscreen.
