### ISSUE TITLE
Provide an option to display actual keycaps vs modified keys

### ISSUE THREAD

**Issue by akitchen** [keycastr/keycastr#187]
There are different cases when users want to broadcast the actual keycaps typed vs how they are resolved when typing. This comes up with shifted and option/alternate key combinations. The PTKeyCode framework bundled with ShortcutRecorder makes this easy enough to do, but it needs to be governed by a user-facing option. See #140 and others for more background.

This is best approached after the MainMenu nib is modernized and easier to work with. #186

**Comment by afkaqualls** [comment]
I support this revision! There are also other ways to looks at this issue. Consider the following use cases:

1. I wish to see the shift key display, using the Default visualizer. This use case would be resolved by the proposed revision expressed here and previously expressed in #104 and #140.
2. I wish to see the shift key display, using the Svelte visualizer. This is currently possible, due to the illumination of the persistently visualized modifier keys, however a difference between the Default and Svelte visualizer is the persistent visualization of keystrokes and the bezel on screen. If I wanted to minimize visual pollution, I have to use the Default visualizer. If I don't mind the persistence of the Svelte visualizer, I now have to accept that my keystrokes won't be cleared until I use a modifier key. This use case should spur another issue ticket for providing an option to fade out key strokes while using the Svelte visualizer.

**Comment by akitchen** [comment]
@afkaqualls Please try out v0.9.10 for the change in shift key behavior. This particular issue is now about making this change in behavior toggle-able

And feel free to open issues for improving the Svelte visualizer; it has been less of a focus.

**Comment by marcotrosi** [comment]
didn't want to open a new issue, this here seems close enough

I have the issue that I need to display the final character my OS would write.
for example when I press `Alt-u` then I don't want to see `Alt-u`, I want to see what `Alt-u` produces, in my case opening square bracket `[`, because I have a custom keyboard layout, otherwise it would be `¨` by default on macOS with German layout.

So it would be great if there was an option that shows the final translated character based on the current keyboard layout selected.

Same for Upper case characters. When I press `Shift-u` then I want to see only `U` and not `Shift-u` or `Shift-U`.

Such configuration would be useful for me because in my Vim screencasts it doesn't matter which keys you pressed, it only matters which characters are behind. So in my example above, `[` has meaning because it's a command in that tool I use, and nobody would understand the keys pressed. 
I hope I was able to explain the problem. Please reach out in case it's not clear.
Have a great day.

**Comment by akitchen** [comment]
https://github.com/keycastr/keycastr/releases/tag/v0.10.0
