### ISSUE TITLE
macOS Big Sur - not working?

### ISSUE THREAD

**Issue by quangv** [keycastr/keycastr#205]
I'm not sure why but the app doesn't seem to work on this Mac. It's running macOS Big Sur 11.2.3

I don't see keystrokes and preferences panes is all messed up in v0.9.10 and v.0.9.9

<img width="419" alt="Screen Shot 2021-05-27 at 11 14 25 AM" src="https://user-images.githubusercontent.com/1171187/119851874-cc069c80-bedc-11eb-99d3-d87808e77a62.png">

in v0.9.8 the preference panes isn't messed up, but I also don't see keystrokes.

**Comment by minspy** [comment]
i have this problem too, and my sys is 11.13.1

**Comment by minspy** [comment]
> i have this problem too, and my sys is 11.13.1

I found a temporary solution. 

1. click the expand button
2. click Update
3. and then click the expand button again, and you will see Display options

**Comment by akitchen** [comment]
The preferences pane issue on Big Sur / 11.x is a weird one. I haven't figured out why it displays that way, but you can still click the `>>` button to access the other preferences panes. Thank you @quangv for the hint that it isn't messed up in v0.9.8; I will look into it more but it could be simply because it was compiled with an older version of the macOS SDK.

I can verify that the app does not have any particular incompatibility with macOS 11.x when it comes to displaying keystrokes. 

For troubleshooting, you could try adjusting your display settings while the app is open (change your screen resolution or plug in an external monitor) as it will have the effect of resetting the position of the default visualizer. @quangv did you perhaps try to move the view to the right side of the screen before it disappeared? This is discussed in #173 and #175 ; a fix for that is in the works but I haven't had much time to dedicate to it lately.

**Comment by akitchen** [comment]
@quangv it should work fine other than the preferences pane glitches -- have you checked your security/accessibility preferences?
