### ISSUE TITLE
Not working on MacOS Monterey

### ISSUE THREAD

**Issue by maheshmnj** [keycastr/keycastr#222]
Hi,
Thanks for this amazing app, But unfortunately this is not working on macOS Monterey, I have enabled  Keycastr in Accessibility settings but I don't see keystrokes, nor start casting does anything.
 
System Info

MacBook Air (M1, 2020)
version 12.1 (21C52) MacOS Monterey

Let me know if you need any further info.

Thanks

**Comment by akitchen** [comment]
There are two likely causes for the app seeming not to work: not receiving keystroke events from macOS due to security settings, or the window being offscreen. Sometimes switching from the Default to the Svelte visualizer can help you figure out which problem it is.

There isn't a compatibility problem with Monterey specifically, but the accessibility settings can be deceiving.

To troubleshoot, I would recommend that you:

- quit the app
- remove KeyCastr from any of the Privacy areas in the Security & Privacy preferences panel (typically the Accessibility or Input Monitoring areas)
- start the app
- when you see the "Keystroke Receiving" dialog from macOS, click "Open System Preferences" or open the Preferences app yourself
- under Input Monitoring, enable KeyCastr by unlocking your preferences and clicking the box next to KeyCastr which should have been automatically added to the list
- when macOS prompts you, restart KeyCastr. Or you can do it manually.

I hope it helps. Some updates to our README are long overdue.

**Comment by maheshmnj** [comment]
Thanks for the prompt reply, Enabling Input monitoring fixed the issue.
We can close this issue.

**Comment by mingchuno** [comment]
The above steps still doesn't work for me. When I tried, I can see the Cmd/Alt/Option/Shift key blink on Svelte UI. But keystrokes doesn't appear. 

<img width="245" alt="Screenshot 2022-09-08 at 19 03 06" src="https://user-images.githubusercontent.com/5472190/189106418-8a4c0dfe-c1b3-47d6-ba92-0bd1731703b4.png">
