### ISSUE TITLE
Sparkle update doesn't work in v0.9.11, need to update manually or via Homebrew

### ISSUE THREAD

**Issue by CanRau** [keycastr/keycastr#229]
<img width="250" alt="Screen Shot 2022-02-22 at 22 10 42" src="https://user-images.githubusercontent.com/5196971/155255868-0d74334a-d71a-4ebf-ae3a-4daa07231249.png">

Updated via Homebrew now, just wanted to share the screenshot

I'm on Big Sur 11.6.3

**Comment by akitchen** [comment]
Thanks for opening this, @CanRau . I changed the title, but for reference the old title was what the user would see: "You're up to date even though newest version is 0.9.12 and I'm on 0.9.11"

It turns out that the Sparkle updater integration was broken a while ago due to some old changes or misconfiguration in the Xcode project file, however the good news is that this is already fixed in v0.9.12 and should work correctly going forward. I'll leave this open until some time after the next release.

**Comment by CanRau** [comment]
Sounds great and happy to hear it was such a quick fix 😃🥳

**Comment by akitchen** [comment]
Verified that updating from v0.9.12 -> v0.9.13 via Sparkle works as expected.
