### ISSUE TITLE
After wake up Mac KeyCastr not working anymore

### ISSUE THREAD

**Issue by VEADoc** [keycastr/keycastr#231]
Lock screen  then wake up my Mac ,KeyCastr was not worked , quit and re-open can't let it work neither

MacBook Pro (16-inch, 2019)  MacOS 12.0.1

**Comment by akitchen** [comment]
Not sure if this is a frequently reoccurring issue, but if the menu bar icon appears light grey (disabled) then the app no longer has accessibility/input monitoring privileges. You'll want to refer to the README's instructions for enabling the app to receive key events.

If the menu bar icon appears to be dark (enabled) then the visualizer may have ended up offscreen for some reason. In this case it should reset itself on next startup, otherwise you can clear the app's stored settings if you are familiar with the `defaults` command in the terminal.
