### ISSUE TITLE
keycastr does not capture keys when typing in a terminal 

### ISSUE THREAD

**Issue by entest-hai** [keycastr/keycastr#246]
I want to capture keystroke when typing inside a terminal but it does not work. I have tried with two M1 macbooks.

**Comment by akitchen** [comment]
KeyCastr is confirmed to work fine with Terminal.app and any app, really. Assuming that things are working fine for you otherwise, I would guess that you're using iTerm or another app with "secure text input" enabled.

If this is the case then you will need to disable that option in order for KeyCastr to receive your input events. Otherwise check that things are working normally in general, perhaps remove KeyCastr from the Input Monitoring sources, restart the app and let macOS correct itself.

**Comment by entest-hai** [comment]
thank you!  I uncheck "secure text input" and it works well now
