### ISSUE TITLE
modifier keys not displaying

### ISSUE THREAD

**Issue by mi-jan** [keycastr/keycastr#272]
Pressing single modifier keys does not display: { **shift, control, option, command** }

Additionally when in "Command Keys Only" mode keyboard shortcuts that use "**shift**+ any key" or "**opt** + any key" do not display. It would be nice to have any combination of modifier keys show up as this would be really helpful for people that do tutorials.

**Comment by akitchen** [comment]
Yes, both statements are correct, this is by design. 

The app currently does not display keystrokes for bare modifier or command keys, and keystrokes modified with shift or opt, but not command or control, are only displayed when "Command keys only" is unchecked because they are not commands.

Supporting bare modifier keypresses is somewhere on the list, there is an older issue about it. However, simple modified keys should not be added to "Command keys only" mode, but we could consider a sub-option to "Include modified keys" although I'm not sure that it would actually make sense in practice. I don't think users would expect to see `⇧9` displayed in a mode when `9` is not.
