### ISSUE TITLE
Catastrophic Error Encountered: Could not create event tap! in v0.9.4

### ISSUE THREAD

**Issue by billfienberg** [keycastr/keycastr#89]
After installing Keycastr from `KeyCastr.app.zip` and granting it permission in System Preferences, I received this error when I tried to open the app. When I click Grant Access, the error goes away, and then immediately reappears. 

![Sceenshot](https://user-images.githubusercontent.com/6130520/27775895-e08c3856-5f6b-11e7-8447-256e8c270545.png)

**Comment by billfienberg** [comment]
I uninstalled the app, and then installed it via Homebrew instead. Now it seems to be working. Closing this issue.

**Comment by thinkxl** [comment]
I installed it from Homebrew and am getting this issue too.

**Comment by 2shortplanks** [comment]
I saw this error too.  No matter how many times I did the "Grant Access" thing it didn't get access.  This is a bug that needs to be fixed.

To manually solve the issue open "System Preferences", click on "Security and Privacy", click on the "Privacy" Tab, pick "Accessibility", then drag the KeyCastr app from wherever you installed it onto the list of apps on the right hand side (you many need to click the Lock in the bottom left corner of System Preferences and enter a password before you do this)

**Comment by akitchen** [comment]
This sounds like an issue with the homebrew upgrade process. We need to see if it is possible to force it to remove and then re-add the app to the list. OS X is trying to protect your privacy and/or security with this mechanism.

If you use homebrew to uninstall the app and install it fresh, does the issue still occur? Is there anyone lurking in the community with homebrew cask expertise that can look at this? I am not likely to be able to do so due to travels for the next couple of weeks.

Unfortunately this is not something that can be worked around within keycastr itself, as this access is needed in order to receive keystroke events.

**Comment by felipe-gdr** [comment]
@akitchen , I've uninstall the app using homebrew and installed it by downloading the .app file, but the error still occurs. 

More details on this (duplicated) issue: https://github.com/keycastr/keycastr/issues/95

**Comment by felipe-gdr** [comment]
update: @2shortplanks tip worked for me 👍

**Comment by sdeken** [comment]
The code that tries to automatically grant access only worked in El Capitan, and because it landed eight days after Sierra hit, it has effectively never worked. Before that, we used to offer to open the Accessibility preferences panel.

We should go back to that behavior unless we can find a way to make the automatic grant work properly.

**Comment by devonzuegel** [comment]
I've tried everything noted above, including deleting the app and re-installing with Homebrew, and also removing and re-adding it under Accessibility. I continue to get this error:

![image](https://user-images.githubusercontent.com/6979755/81228519-0b490f00-8fa3-11ea-9cc6-1b684e52a30b.png)

I'm on Catalina `10.15.4`. Any ideas?

**Comment by jacobsandlund** [comment]
I'm in the same boat as @devonzuegel on 10.15.4 and tried everything. Re-installing via Homebrew, installing via GitHub releases, Adding it to the accessibility API via dragging or the select file menu, toggling the checkbox, logging out, restarting.

**Comment by matthewhuang97** [comment]
Worked for me on 10.15.2, if that helps with narrowing things down!

**Comment by mwichary** [comment]
It works for me on 10.15.4 right now, although I installed it when I was still on 10.14.

**Comment by oneraghavan** [comment]
In addition to accessibility permission, input monitoring permission should also be given. OSX version 10.15.6. 

I was getting the same error as everyone, then gave permission input monitoring and everything worked
